title: Xu Yang
position: Associate Professor
affiliation: PALM, CS, SEU
email: s170018(at)e.ntu.edu.sg
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=SqdxMH0AAAAJ&hl=en
avatar: ./assets/img/Picture1.png
remote_theme: yaoyao-liu/minimal-light
