title: Xu Yang; 杨旭
position: Associate Professor
affiliation: PALM, CS, SEU
email: s170018(at)e.ntu.edu.sg; xuyangseu@ieee.org
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=SqdxMH0AAAAJ&hl=en
github_link: https://github.com/yangxuntu
avatar: ./images/yangxu.jpeg
remote_theme: yaoyao-liu/minimal-light
